### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by r00bit** [lkytal/PepNet#2]
After running the following command:
`python denovo.py --input example.mgf --model model.h5 --output example_prediction.tsv`
 I get this error
lib/python3.7/site-packages/keras/engine/input_spec.py", line 200, in assert_input_compatibility
        raise ValueError(f'Layer "{layer_name}" expects {len(input_spec)} input(s),'

    V**alueError: Layer "denovo" expects 4 input(s), but it received 3 input tensors. Inputs received**: [<tf.Tensor 'IteratorGetNext:0' shape=(None, None, None) dtype=float32>, <tf.Tensor 'IteratorGetNext:1' shape=(None, None) dtype=float32>, <tf.Tensor 'IteratorGetNext:2' shape=(None, None) dtype=float32>]

I couldn't figure out how to fix it, could you please let me know how I can fix it?
I am using the same inputs and pretrained model provided by the author. 
Thanks!

**Comment by lkytal** [comment]
Did you use the correct corresponding version of the model files? I've updated this repository several times

**Comment by r00bit** [comment]
I downloaded the code from github, where can I get the last version?
thanks!

**Comment by lkytal** [comment]
https://zenodo.org/record/7869847 , also listed in readme

**Comment by r00bit** [comment]
Hello, 
the de novo algorithm works pretty well on the model.h5 released by you using the following command. 

python denovo.py --input example.mgf --model model.h5 --output example_prediction.tsv

However, when I trained model on different datasets or even the train.py and validation.py datasets posted by you, it created a model that doesn't match with the post processing function. Here is the bug:
` predictions = model.predict(data_seq(spectra, input_processor, batch_size, xonly=True), verbose=1)
 
    for rst, sp in zip(predictions, spectra):
        ms, c = sp['mass'], sp['charge']

        # run post correction
        pep, pos, positional_score = post_correction(rst, ms, c)`
it returns this error:
Traceback (most recent call last):
  File "denovo.py", line 229, in <module>
    peps, ppeps, scores, pscores, ppms, _ = denovo(model, spectra, args.batch_size)
  File "denovo.py", line 182, in denovo
    pep, pos, positional_score = post_correction(rst, ms, c)
  File "denovo.py", line 73, in post_correction
    pep = topep(seq)
  File "/PepNet-master/utils.py", line 169, in topep
    return ''.join(map(lambda n: id2amino[n], seq)).strip("*[]")
  File "/PepNet-master/utils.py", line 169, in <lambda>
    return ''.join(map(lambda n: id2amino[n], seq)).strip("*[]")
KeyError: 121

Because the prediction is a list with length of 8 and with eight different shape: (124, 1)
prediction shape:
(124, 32)
(124, 1)
(124, 8)
(124, 21)
(124, 21, 30)
(124, 400)
(124, 32, 24)
124 is the number of spectra in the train.py 
Could you please let me know how I can fix it?
Thanks!
